name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run rubocop
        run: bundle exec rubocop --parallel

      - name: Set up database
        run: bundle exec rails db:setup
        env:
          RAILS_ENV: test

      - name: Run tests
        run: bundle exec rails test:all
        env:
          RAILS_ENV: test
